## TensorFlow 1.X




### Installing TensorFlow 1.X



In [20]:
!pip install tensorflow-gpu==1.13.1

  Using cached https://files.pythonhosted.org/packages/7b/b1/0ad4ae02e17ddd62109cd54c291e311c4b5fd09b4d0678d3d6ce4159b0f0/tensorflow_gpu-1.13.1-cp36-cp36m-manylinux1_x86_64.whl
  Found existing installation: tensorflow-gpu 2.0.0a0
    Uninstalling tensorflow-gpu-2.0.0a0:
      Successfully uninstalled tensorflow-gpu-2.0.0a0


In [1]:
import tensorflow as tf

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

In [2]:
tf.__version__

'1.13.1'

### Constants

#### Defining a constant

In [3]:
# Defining a TensorFlow constant
tensor = tf.constant([[23, 4], [32, 51]])

In [4]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [5]:
# If a session is not initialized, we cannot access the values of the constant
tensor.eval()

ValueError: ignored

#### Getting the values of a constant

In [10]:
session = tf.Session()

In [11]:
session.run(tf.global_variables_initializer())

In [13]:
tensor_value = session.run(tensor)

In [14]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variables

#### Defining a variable

In [15]:
# Defining a TensorFlow variable
variable = tf.Variable([[30, 20], [10, 45]])

Instructions for updating:
Colocations handled automatically by placer.


In [16]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [17]:
# If a session is not initialized, we cannot access the values of the variable
variable.eval()

ValueError: ignored

#### Getting the values of a variable

In [18]:
# Initializing a session
session = tf.Session()

In [19]:
# Initializing ALL the variables from the session
session.run(tf.global_variables_initializer())

In [20]:
# Running the eval method on the environment with the initialized session to retrieve values from it
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [24]:
!pip install tensorflow-gpu==2.0.0-alpha0

  Using cached https://files.pythonhosted.org/packages/1a/66/32cffad095253219d53f6b6c2a436637bbe45ac4e7be0244557210dc3918/tensorflow_gpu-2.0.0a0-cp36-cp36m-manylinux1_x86_64.whl
  Found existing installation: tensorflow-gpu 1.13.1
    Uninstalling tensorflow-gpu-1.13.1:
      Successfully uninstalled tensorflow-gpu-1.13.1


In [1]:
import tensorflow as tf
import numpy as np

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or 

In [2]:
tf.__version__

'2.0.0-alpha0'

### Constants

#### Defining a constant

In [3]:
# Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [4]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [5]:
# Getting the shape of a tensor
tensor_20.shape

TensorShape([2, 2])

#### Getting the values of a constant

In [6]:
# Getting the values straight from a TensorFlow constant with numpy, and without the need of a session
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [7]:
# We are able to convert a numpy array back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])

In [8]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [9]:
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variables

#### Defining a variable

In [10]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Getting the values of a variable

In [11]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing a specific value in the variable

In [12]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [13]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operations with tensors

In [14]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=30, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Addition between a scalar and a tensor

In [15]:
tensor + 2

<tf.Tensor: id=33, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplication between a scalar and a tensor

In [16]:
tensor * 5

<tf.Tensor: id=36, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Using Numpy functions on TensorFlow tensors

In [17]:
# Getting the squares of all numbers in a TensorFlow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [18]:
# Getting the square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product between two tensors

In [19]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings in TensorFlow 2.0

In [20]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=44, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [21]:
tf.strings.length(tf_string)

<tf.Tensor: id=46, shape=(), dtype=int32, numpy=10>

In [22]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=51, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Storing arrays of strings

In [23]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [24]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
